<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformCommandLineArguments>--minimum-expected-tests 1</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <ItemGroup>

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PxtlCa.SystemCollectionsExtensions" Version="0.3.4" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageReference Include="xunit.v3.runner.console" Version="3.2.2" />
    <PackageReference Include="FluentAssertions" Version="7.2.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\MnkeyFog.CommandLine\MnkeyFog.CommandLine.csproj" />
    <ProjectReference Include="..\..\src\MnkeyFog.Model\MnkeyFog.Model.csproj" />
  </ItemGroup>

</Project>