name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # NOTICE: "windows-latest" requests are being redirected to "windows-2025-vs2026" by June 15, 2026
        os: [ubuntu-latest, windows-2025-vs2026]

    steps:
      # There is a validation error happening on Windows only so I assume that
      # disabling autocrlf will fix it.
      - name: Disable autocrlf
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
